### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Your schedule currently amounts to 11 days, while you have 14 workdays available. Do you think you can get this all done in that 11-day time frame?
I would flip Reviews and Search in terms of the order. I think Search might not take as long as the Reviews MVP and the latter will add more depth and atmosphere to your site.
I suggest adding specifics regarding your Host Lodging and Reservations MVPS: what information can be updated for Lodgings and Reservations. Guests? Also, of these MVPs, are users required to be logged in?
No Bonuses Currently. Add some Bonuses in there! Maybe Messages, WishLists, or Experiences near your Reservation. Maybe Profile (see below).

1. Landing Page/User Auth
    1. I would consider refactoring your update/destroy options for an account and the profile page into a separate MVP. Creation of an account lends to the Sign Up functionality of the User Auth MVP. The rest would fit as a Profile MVP and could be added as a Bonus.
2. Host Lodging
    1. I would say Host Lodging fulfills a full CRUD cycle as well, so you can add READ

**Comment by derek-2** [comment]
@keginzburg I refactored my MVP List
