### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#3]
# Database Schema
- [ ] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
For some of your tables, you’ve added associations, but have not specified what tables your foreign keys are referring to. I would add these for clarification.

1. Users
    1. Will you be integrating searching users at all? If so, possibly indexing their first and last name?
2. Bookings
    1. I believe you want the following rows (in Bookings) within this table:
        1. check_in_date, check_out_date
    2. Also, will you keep track of the total price here depending on check in and checkout and the number of guests staying during a booking?
3. Listings
    1. Again, I believe some rows (check_in_date, check_out_date) belong in Bookings instead.
    2. Will num_guests row refer to the maximum number of guests per listing?
4. Reviews
    1. Not a big deal, but do we want the specific ratings to be floats or integers, while main rating would be a float?
    2. check-in should be check_in
    3. Should body be a string or text data_type?

**Comment by derek-2** [comment]
- I added the tables the foreign keys are coming from
- I added moved check_in_date and check_out_date from listings to bookings
- I also added the num_guests to bookings, and total_price, which will be calculated using the num_guests and difference in check_in_date and check_out_date
- In listings, i renamed num_guests to max_num_guests
- For check_in and check_out date in listings, I was planning to do something along the lines of showing dates where the listing is available.
- I also edited the reviews' data types
