### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#4]
# Sample State
- [X] State shape is flat!
- [X] State’s keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [ ] `session`
    - [ ] `errors` (here or in `ui`)
    - [ ] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
Your listing with an id of 1 has a key of 9000 in your listing’s slice of state...

Following potential changes in your database schema, you might need to move certain information from one slice of state to another (checkInDate, checkOutDate...).

Please add errors, UI, and session slices in your sample state as well. You can look to bluebird for more guidance on this: [Bluebird Sample State](https://github.com/appacademy/bluebird/wiki/sample-state)

**Comment by derek-2** [comment]
- I fixed the key to match the value's id in listings
- I added session, errors, and ui slices to my state
- I added availableDays to listings as an array, I'm not sure if storing it in an array is possible/a good idea

**Comment by keginzburg** [comment]
I would avoid adding all of that date data to an array in your backend or state. Instead, I would add the check-in and checkout date from your backend to your bookings state as your schema already has those datetime rows. When a user tries to make a booking, you can cross reference a listing's current bookings and their respective checkin/checkout dates to see if they conflict. Once you add that, this should be good.
