### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

## Comments
Bookings

1. What is the conventional URI pattern when POST to your backend? You currently are POSTing to /api/bookings/:id

Listings

1. Will you need a custom route when it comes to searching for specific listings? How can you implement this?
2. Do you need a GET /api/listings/:id route to pull information for a single listing?

**Comment by derek-2** [comment]
- I changed the POST bookings url
- I added a couple of additional routes to listings for specific searches
