### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
Looks pretty good so far. Format wise, you can use backticks to write your Components after your Frontend Routes.

Will you need any frontend routes and components to account for a host having multiple listings, in order to show the host all of the bookings for separate listings?
Also any frontend route/components for a host to introduce/make a new listing?

**Comment by derek-2** [comment]
- I added a Recommendations component to the home page
- I added the frontend route '/users/:userId/bookings' for a host to see all the bookings for each listing. I'm not sure what to call the components.
-  I want to have a component that shows all of their listings.
    - For each listing, show all the bookings for it

**Comment by keginzburg** [comment]
For the component that shows all of a host's listings, do we also want a '/users/:userId/listings' route? Otherwise, this looks pretty solid.
