### ISSUE TITLE
Issue #07 - Splash/User Auth

### ISSUE THREAD

**Issue by keginzburg** [derek-2/BreakfastnBed#7]
Hey Derek, here are my notes for your Splash Page and User Auth:

Functionality--

1. When signing up, users can currently make accounts with emails that aren’t in email format. I would try and correct this before moving on. This can be done on your front end if necessary.

2. Also, you do have some error handling for email and password when signing up. Are you planning on putting error handling into effect for the “First name” and “Last name” fields as well?

3. Your error handling for login says “Wrong Credentials“ when trying to input nothing at all. I would attempt some conditional error handling that renders “Email and Password can’t be blank” instead if those fields are left blank and “Wrong Credentials” if they aren’t blank and the current user input doesn’t match an account on your backend.

4. Your Demo Login does not seem to be working on Heroku. I would absolutely fix this before moving on.

5. Unless you plan on making the Technologies and About footer links active, I would remove them for now. It seems like you’ll only be using the Personal Links section.

6. Just want to make a general note that you should be integrating a search bar on your Splash in a future MVP.

CSS--

7. I would change your logo to the AirBnb logo and your specific clone’s name, Bedfast. I would try to source a higher-quality logo as well.

8. Your footer definitely needs some more CSS styling to more closely resemble AirBnb’s look.

9. I think your splash is also missing key styling for the Sign Up and Login form modals. I would attempt to get it as close as possible to AirBnb without integrating some of their extra functionality (Continue with Facebook, Continue with Google, etc.). When these modals render, they should also create a slightly opaque gradient over the splash below and you should be able to click outside of the modals to close them.

10. At some point in the future, I would try to implement some basic HTML elements on your Splash that resemble AirBnb’s Questions about Hosting image and link. You could replace it with “Questions about the Developer” and have it link to your portfolio site which you’ll create in the last week of the program.

You should address the functionality issues (at the very least) before moving on to your next MVP.

**Comment by derek-2** [comment]
I attempted to fix everything except my footer. Page is buggy when resizing though.
